[package]
name = "ply"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
toml = "0.9"
serde = "1.0"
ureq = "3.1"
anyhow = "1.0"
camino = "1.1"
chrono = "0.4"
url = "2.5"
bon = "3.7"
