[package]
name = "ply"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
toml = { version = "0.9", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
ureq = "3.1"
anyhow = "1.0"
camino = "1.1"
chrono = { version = "0.4", features = ["serde"] }
url = { version = "2.5", features = ["serde"] }
bon = "3.7"
scraper = "0.24.0"
regex = "1.11.2"
